package models

import (
	"encoding/json"
	"encoding/xml"
)

type SdnList struct {
	XMLName           xml.Name `xml:"sdnList" json:"-"`
	Xsi               string   `xml:"xsi,attr" json:"-"`
	Xmlns             string   `xml:"xmlns,attr" json:"-"`
	PublshInformation struct {
		PublishDate string `xml:"Publish_Date" json:"publishDate"` // 04/27/2023
		RecordCount string `xml:"Record_Count" json:"recordCount"` // 12209
	} `xml:"publshInformation"`
	SdnEntry []SdnEntry `xml:"sdnEntry" json:"sdnEntry"`
}

type SdnEntry struct {
	Uid         int    `xml:"uid" json:"uid"`           // 36, 173, 306, 424, 475, 4...
	LastName    string `xml:"lastName" json:"lastName"` // AEROCARIBBEAN AIRLINES, A...
	SdnType     string `xml:"sdnType" json:"sdnType"`   // Entity, Entity, Entity, E...
	ProgramList struct {
		Program []string `xml:"program" json:"program"` // CUBA, CUBA, CUBA, CUBA, C...
	} `xml:"programList" json:"programList"`
	AkaList struct {
		Aka []struct {
			Uid       int    `xml:"uid" json:"uid"`             // 12, 57, 219, 220, 471, 47...
			Type      string `xml:"type" json:"type"`           // a.k.a., a.k.a., a.k.a., a...
			Category  string `xml:"category" json:"category"`   // strong, strong, weak, str...
			LastName  string `xml:"lastName" json:"lastName"`   // AERO-CARIBBEAN, AVIA IMPO...
			FirstName string `xml:"firstName" json:"firstName"` // Muhammad, Ayman, Ahmad Fu...
		} `xml:"aka" json:"aka"`
	} `xml:"akaList" json:"akaList"`
	AddressList struct {
		Address []struct {
			Uid             int    `xml:"uid" json:"uid"`                         // 25, 129, 199, 200, 201, 2...
			City            string `xml:"city" json:"city"`                       // Havana, London, Zurich, M...
			Country         string `xml:"country" json:"country"`                 // Cuba, United Kingdom, Swi...
			Address1        string `xml:"address1" json:"address1"`               // Ibex House, The Minories,...
			PostalCode      string `xml:"postalCode" json:"postalCode"`           // EC3N 1DY, CH-8022, E-2803...
			Address2        string `xml:"address2" json:"address2"`               // Ibex House, The Minories,...
			StateOrProvince string `xml:"stateOrProvince" json:"stateOrProvince"` // Quebec, AB, AB, Valle, Va...
			Address3        string `xml:"address3" json:"address3"`               // Vedado, Plaza de la Revol...
		} `xml:"address" json:"address"`
	} `xml:"addressList" json:"addressList"`
	IdList struct {
		ID []struct {
			Uid            int    `xml:"uid" json:"uid"`                       // 19525, 136109, 136110, 13...
			IdType         string `xml:"idType" json:"idType"`                 // Company Number, SWIFT/BIC...
			IdNumber       string `xml:"idNumber" json:"idNumber"`             // 01074897, HAVIGB2L, www.h...
			IdCountry      string `xml:"idCountry" json:"idCountry"`           // United Kingdom, Egypt, Eg...
			IssueDate      string `xml:"issueDate" json:"issueDate"`           // 18 Jan 1984, 21 Jun 1992,...
			ExpirationDate string `xml:"expirationDate" json:"expirationDate"` // 17 Jul 2011, 27 Feb 2001,...
		} `xml:"id" json:"id"`
	} `xml:"idList" json:"idList"`
	FirstName       string `xml:"firstName" json:"firstName"` // Abu, Shaykh Umar Abd, Dr....
	Title           string `xml:"title" json:"title"`         // Director of PALESTINE LIB...
	DateOfBirthList struct {
		DateOfBirthItem []struct {
			Uid         int    `xml:"uid" json:"uid"`                 // 1000, 1001, 1003, 40120, ...
			DateOfBirth string `xml:"dateOfBirth" json:"dateOfBirth"` // 10 Dec 1948, 03 May 1938,...
			MainEntry   string `xml:"mainEntry" json:"mainEntry"`     // true, true, true, true, t...
		} `xml:"dateOfBirthItem" json:"date_of_birth_item"`
	} `xml:"dateOfBirthList" json:"dateOfBirthList"`
	PlaceOfBirthList struct {
		PlaceOfBirthItem []struct {
			Uid          int    `xml:"uid" json:"uid"`                   // 1002, 1004, 1005, 1008, 1...
			PlaceOfBirth string `xml:"placeOfBirth" json:"placeOfBirth"` // Egypt, Giza, Egypt, Nahia...
			MainEntry    string `xml:"mainEntry" json:"mainEntry"`       // true, true, true, true, t...
		} `xml:"placeOfBirthItem" json:"place_of_birth_item"`
	} `xml:"placeOfBirthList" json:"placeOfBirthList"`
	NationalityList struct {
		Nationality []struct {
			Uid       int    `xml:"uid" json:"uid"`             // 40121, 39681, 5416, 43323...
			Country   string `xml:"country" json:"country"`     // Egypt, Mauritania, Palest...
			MainEntry string `xml:"mainEntry" json:"mainEntry"` // true, true, true, true, t...
		} `xml:"nationality" json:"nationality"`
	} `xml:"nationalityList" json:"nationalityList"`
	Remarks    string `xml:"remarks" json:"remarks"` // (Linked To: HIZBALLAH), (...
	VesselInfo struct {
		CallSign               string `xml:"callSign" json:"callSign"`                             // CL2192, CL2059, T2EU4, 9H...
		VesselType             string `xml:"vesselType" json:"vesselType"`                         // Tug, General Cargo, Tug, ...
		VesselFlag             string `xml:"vesselFlag" json:"vesselFlag"`                         // Cuba, Panama, Cuba, Iran,...
		VesselOwner            string `xml:"vesselOwner" json:"vesselOwner"`                       // Samir de Navegacion S.A.,...
		GrossRegisteredTonnage string `xml:"grossRegisteredTonnage" json:"grossRegisteredTonnage"` // 212, 1865, 189, 56068, 56...
		Tonnage                string `xml:"tonnage" json:"tonnage"`                               // 2595, 99144, 99030, 99094...
	} `xml:"vesselInfo" json:"vesselInfo"`
	CitizenshipList struct {
		Citizenship []struct {
			Uid       int    `xml:"uid" json:"uid"`             // 1219, 1222, 1229, 1231, 1...
			Country   string `xml:"country" json:"country"`     // Egypt, Egypt, Saudi Arabi...
			MainEntry string `xml:"mainEntry" json:"mainEntry"` // true, true, true, true, t...
		} `xml:"citizenship" json:"citizenship"`
	} `xml:"citizenshipList" json:"citizenshipList"`
}

func (sdn *SdnEntry) Marshal() string {
	b, _ := json.Marshal(*sdn)
	return string(b)
}
